<a href="https://colab.research.google.com/github/kaustubholpadkar/MyTorch/blob/modules%2Ftensors_autodiff/Tensors_%26_Auto_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
tens1 = torch.ones(5, 3)

In [3]:
tens1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
tens2 = torch.empty_like(tens1)

In [5]:
tens2

tensor([[4.4082e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 7.0065e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.0000e+00]])

In [6]:
tens3 = torch.rand(2, 3)
tens3

tensor([[0.6482, 0.3553, 0.6220],
        [0.9070, 0.7256, 0.4556]])

In [7]:
tens4 = torch.randn(3, 2)
tens4

tensor([[ 0.4795,  0.2953],
        [ 0.3029,  1.7274],
        [-1.1048,  0.1878]])

### Auto Differentiation

In [8]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [9]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
print(y.grad_fn)

In [11]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [12]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### Gradients

In [0]:
out.backward()

In [14]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [19]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x * 2
print(y)
print(y.data.norm())

tensor([ 1.9344, -0.5484,  1.0987], requires_grad=True)
tensor([ 3.8688, -1.0968,  2.1973], grad_fn=<MulBackward0>)
tensor(4.5824)


In [16]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1523.3563, 1021.0194,  146.1697], grad_fn=<MulBackward0>)


In [0]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

In [18]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [20]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


#### Examples

In [0]:
x = torch.tensor(3.0, requires_grad=True)

In [0]:
y = 5 * x * x

In [26]:
y

tensor(45., grad_fn=<MulBackward0>)

In [0]:
y.backward()

In [28]:
x.grad

tensor(30.)